theme = "devfest-theme-hugo"
date = "2019-03-30"
title = "NoOps Japan"
#...
# description = "The DevFest, or 'Developers Festival', is a technical conference for developers. It is aimed at students, professionals or simply curious technophiles."


enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

googleAnalytics = "UA-XXXXXXXX-X"

[params]
    title = "NoOps Japan Community"
    date = "2019-06-23"
    description = "NoOps Japanでは 「システム運用保守の'嬉しくないこと'をなくそう！」 をテーマに、 NoOpsを実現するための技術・設計手法・開発運用保守サイクル・ツールや考え方・事例などを共有していきたいと考えています。"
    images = ["/images/top-image.png"]
    email = ""
    keywords = "NoOps, DevOps, Agile, Azure, AWS, GCP"
    copyright = "NoOps Japan Community"
    cfpUrl = "https://conference-hall.io/public/event/HJRThubF4uYPkb7jSUxi"
    subscriptionUrl = "http://eepurl.com/dps1j5"
    appleTouchIcon = "/images/top-image.png"
    favicon32 = "/images/favicon.ico"
    favicon16 = "/images/favicon.ico"
    manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#673ab7"

[params.logos]
    jumbo = "/images/noops-header2.png"
    header = "/images/noops-header2.png"
    footer = "/images/noops-header2.png"

[languages]
[languages.en]
    weight = 1
    languageName = "gb"

[taxonomies]
  tag = "NoOps"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

